name: vendor
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  mime: ^1.0.5
  adaptive_theme: 3.6.0
  app_to_foreground: ^0.0.3
  args: ^2.5.0
  assets_audio_player: ^3.1.1
  awesome_notifications: 0.9.3+1
  basic_utils: ^5.7.0
  blue_thermal_printer: ^1.2.3
  cached_network_image: ^3.3.1
  cloud_firestore: ^5.0.2
  cool_alert: ^2.0.1
  country_picker: 2.0.26
  cupertino_icons: ^1.0.8
  currency_formatter: ^2.2.1
  custom_clippers: ^2.0.0
  dartx: ^1.2.0
  dio: ^5.4.3+1
  dotted_border: ^2.1.0
  dotted_line: ^3.2.2
  double_back_to_close: ^2.0.0
  file_picker: ^8.0.5
  file_sizes: ^1.0.6
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_crashlytics: ^4.0.2
  firebase_messaging: ^15.0.2
  firestore_chat: ^0.1.2
  dash_chat_2: ^0.0.21
  fl_chart: ^0.68.0
  flag: ^7.0.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.3.0
  flutter_icons:
    git:
      url: https://github.com/imclerran/flutter-icons.git
      ref: dart-3
  flutter_image_compress: ^2.3.0
  flutter_inappwebview: ^6.0.0
  flutter_lifecycle_detector: ^0.0.6
  flutter_localizations:
    sdk: flutter
  flutter_overboard: ^3.1.3
  flutter_sim_country_code: ^0.1.2
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.10+1
  flutter_typeahead: ^5.2.0
  flutter_widget_from_html_core: ^0.15.1
  fluttertoast: ^8.2.6
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.6
  image_picker: 1.1.2
  in_app_review: ^2.0.9
  inspection: ^0.0.13
  intl: ^0.19.0
  jiffy: ^6.3.1
  line_icons: ^2.0.3
  localize_and_translate: ^5.1.2
  map_launcher: ^3.3.1
  masonry_grid: ^1.0.0
  numeral: ^3.0.0
  package_info_plus: ^8.0.0
  permission_handler: ^11.3.1
  pin_code_fields: ^8.0.1
  pinch_zoom: ^2.0.0
  pretty_dio_logger: ^1.3.1
  printing: ^5.13.1
  qr_code_scanner: ^1.0.1
  #quill_html_editor: ^2.2.8
  flutter_quill: ^10.1.5
  random_string: ^2.3.1
  rx_shared_preferences: ^3.1.0
  shared_preferences: ^2.2.3
  singleton: ^0.0.3-nullsafety
  slide_countdown: ^2.0.0-dev+2
  stacked: 3.4.3
  supercharged: ^2.1.1
  upgrader: ^10.3.0
  url_launcher: ^6.3.0
  velocity_x: 4.2.1
  auto_size_text: ^3.0.0

dependency_overrides:
  intl: ^0.18.1
  http: ^0.13.0
  uuid: ^4.3.3
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  translator: ^1.0.0

#flutter_icons:
#  android: "launcher_icon"
#  ios: true
#  remove_alpha_ios: true
#  image_path: "assets/images/app_icon.png"
#  adaptive_icon_foreground: "assets/images/app_icon.png"
#  adaptive_icon_background: "#5e17eb"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
    - assets/lang/