// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN1l_62idRnhFETC9dOhy9QfoWFxMj9VQ',
    appId: '1:694541016404:web:a7a5517582c05e68367cc1',
    messagingSenderId: '694541016404',
    projectId: 'mealknightbackend',
    authDomain: 'mealknightbackend.firebaseapp.com',
    storageBucket: 'mealknightbackend.appspot.com',
    measurementId: 'G-05NF03D73B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz3PwVkPI1wxKlInHxFIB4gQY321-vW7M',
    appId: '1:694541016404:android:7b2384ce3ce70470367cc1',
    messagingSenderId: '694541016404',
    projectId: 'mealknightbackend',
    storageBucket: 'mealknightbackend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxGk6iNLm7tEGiL9F4HHpsRK1x1k6dyDY',
    appId: '1:694541016404:ios:1aa6b5b1a28f424b367cc1',
    messagingSenderId: '694541016404',
    projectId: 'mealknightbackend',
    storageBucket: 'mealknightbackend.appspot.com',
    iosBundleId: 'online.mealknight.vendor',
  );
}
